ALTER TABLE packing_templates ALTER COLUMN priority TYPE VARCHAR(20);

INSERT INTO packing_templates (climate_zone, category, item_label, priority) VALUES
-- Tropical
('tropical', 'clothing', 'Lightweight breathable t-shirts', 'must'),
('tropical', 'clothing', 'Shorts and linen trousers', 'must'),
('tropical', 'clothing', 'Flip flops and sandals', 'must'),
('tropical', 'clothing', 'Light rain jacket', 'recommended'),
('tropical', 'clothing', 'Swimwear', 'must'),
('tropical', 'toiletries', 'High SPF sunscreen (SPF 50+)', 'must'),
('tropical', 'toiletries', 'Insect repellent (DEET-based)', 'must'),
('tropical', 'toiletries', 'After-sun lotion', 'recommended'),
('tropical', 'toiletries', 'Rehydration sachets', 'recommended'),
('tropical', 'documents', 'Travel insurance with medical cover', 'must'),
('tropical', 'other', 'Reusable water bottle', 'must'),
('tropical', 'other', 'Portable fan', 'optional'),
-- Temperate
('temperate', 'clothing', 'Layering base shirts', 'must'),
('temperate', 'clothing', 'Mid-layer fleece or jumper', 'must'),
('temperate', 'clothing', 'Waterproof jacket', 'must'),
('temperate', 'clothing', 'Comfortable walking shoes', 'must'),
('temperate', 'clothing', 'Smart casual outfit for dinners', 'recommended'),
('temperate', 'toiletries', 'Moisturiser for dry air', 'recommended'),
('temperate', 'toiletries', 'Lip balm', 'recommended'),
('temperate', 'documents', 'Travel insurance', 'must'),
('temperate', 'other', 'Compact umbrella', 'must'),
('temperate', 'other', 'Day backpack', 'must'),
-- Cold
('cold', 'clothing', 'Thermal base layer top and bottom', 'must'),
('cold', 'clothing', 'Heavy down jacket', 'must'),
('cold', 'clothing', 'Wool socks (3+ pairs)', 'must'),
('cold', 'clothing', 'Waterproof insulated boots', 'must'),
('cold', 'clothing', 'Gloves and thermal beanie', 'must'),
('cold', 'clothing', 'Fleece mid-layer', 'must'),
('cold', 'clothing', 'Neck gaiter or scarf', 'recommended'),
('cold', 'toiletries', 'Heavy duty moisturiser', 'must'),
('cold', 'toiletries', 'Lip balm SPF', 'must'),
('cold', 'toiletries', 'Hand cream', 'recommended'),
('cold', 'other', 'Hand warmers', 'recommended'),
('cold', 'other', 'Thermos flask', 'recommended'),
-- Arid
('arid', 'clothing', 'Loose long-sleeve shirts for sun cover', 'must'),
('arid', 'clothing', 'Wide brim hat', 'must'),
('arid', 'clothing', 'Lightweight long trousers', 'must'),
('arid', 'clothing', 'Closed-toe sandals', 'recommended'),
('arid', 'toiletries', 'SPF 50+ sunscreen', 'must'),
('arid', 'toiletries', 'Lip balm with SPF', 'must'),
('arid', 'toiletries', 'Eye drops for dry air', 'recommended'),
('arid', 'other', 'Large reusable water bottle (2L)', 'must'),
('arid', 'other', 'Electrolyte tablets', 'must'),
('arid', 'other', 'Sunglasses UV400', 'must'),
-- Variable
('variable', 'clothing', 'Mix of light and warm layers', 'must'),
('variable', 'clothing', 'Waterproof jacket', 'must'),
('variable', 'clothing', 'Versatile walking shoes', 'must'),
('variable', 'clothing', 'Light scarf (doubles as blanket)', 'recommended'),
('variable', 'toiletries', 'All-weather moisturiser', 'recommended'),
('variable', 'documents', 'Printed hotel and flight confirmations', 'recommended'),
('variable', 'other', 'Compact umbrella', 'must'),
('variable', 'other', 'Portable power bank', 'must'),
-- Universal documents (add to all trips regardless of climate)
('tropical', 'documents', 'Passport with 6 months validity', 'must'),
('temperate', 'documents', 'Passport with 6 months validity', 'must'),
('cold', 'documents', 'Passport with 6 months validity', 'must'),
('arid', 'documents', 'Passport with 6 months validity', 'must'),
('variable', 'documents', 'Passport with 6 months validity', 'must'),
('tropical', 'electronics', 'Universal travel adapter', 'must'),
('temperate', 'electronics', 'Universal travel adapter', 'must'),
('cold', 'electronics', 'Universal travel adapter', 'must'),
('arid', 'electronics', 'Universal travel adapter', 'must'),
('variable', 'electronics', 'Universal travel adapter', 'must'),
('tropical', 'electronics', 'Portable power bank', 'must'),
('temperate', 'electronics', 'Portable power bank', 'must'),
('cold', 'electronics', 'Portable power bank 20000mAh for cold battery drain', 'must'),
('arid', 'electronics', 'Portable power bank', 'must'),
('variable', 'electronics', 'Portable power bank', 'must');
