-- CITIES (20 cities with realistic data)
INSERT INTO cities (name, country, region, timezone, currency_code, avg_daily_cost_usd, popularity_score, climate_zone, latitude, longitude) VALUES
('Mumbai', 'India', 'South Asia', 'Asia/Kolkata', 'INR', 45.00, 9, 'tropical', 19.076090, 72.877426),
('Delhi', 'India', 'South Asia', 'Asia/Kolkata', 'INR', 40.00, 9, 'variable', 28.613939, 77.209023),
('Goa', 'India', 'South Asia', 'Asia/Kolkata', 'INR', 55.00, 8, 'tropical', 15.299326, 74.123996),
('Jaipur', 'India', 'South Asia', 'Asia/Kolkata', 'INR', 35.00, 8, 'arid', 26.912434, 75.787270),
('Manali', 'India', 'South Asia', 'Asia/Kolkata', 'INR', 30.00, 7, 'cold', 32.241457, 77.188720),
('Paris', 'France', 'Western Europe', 'Europe/Paris', 'EUR', 180.00, 10, 'temperate', 48.856614, 2.352222),
('Rome', 'Italy', 'Southern Europe', 'Europe/Rome', 'EUR', 150.00, 10, 'temperate', 41.902782, 12.496366),
('Barcelona', 'Spain', 'Southern Europe', 'Europe/Madrid', 'EUR', 140.00, 9, 'temperate', 41.385064, 2.173403),
('Amsterdam', 'Netherlands', 'Western Europe', 'Europe/Amsterdam', 'EUR', 160.00, 9, 'temperate', 52.367573, 4.904139),
('Prague', 'Czech Republic', 'Central Europe', 'Europe/Prague', 'CZK', 90.00, 8, 'temperate', 50.075538, 14.437800),
('Tokyo', 'Japan', 'East Asia', 'Asia/Tokyo', 'JPY', 130.00, 10, 'temperate', 35.689487, 139.691706),
('Bangkok', 'Thailand', 'Southeast Asia', 'Asia/Bangkok', 'THB', 60.00, 9, 'tropical', 13.756331, 100.501765),
('Bali', 'Indonesia', 'Southeast Asia', 'Asia/Makassar', 'IDR', 55.00, 9, 'tropical', -8.340539, 115.091949),
('Singapore', 'Singapore', 'Southeast Asia', 'Asia/Singapore', 'SGD', 160.00, 9, 'tropical', 1.352083, 103.819836),
('Dubai', 'UAE', 'Middle East', 'Asia/Dubai', 'AED', 200.00, 9, 'arid', 25.204849, 55.270783),
('New York', 'USA', 'North America', 'America/New_York', 'USD', 250.00, 10, 'variable', 40.712776, -74.005974),
('London', 'UK', 'Western Europe', 'Europe/London', 'GBP', 220.00, 10, 'temperate', 51.507351, -0.127758),
('Sydney', 'Australia', 'Oceania', 'Australia/Sydney', 'AUD', 190.00, 9, 'temperate', -33.868820, 151.209296),
('Reykjavik', 'Iceland', 'Northern Europe', 'Atlantic/Reykjavik', 'ISK', 210.00, 7, 'cold', 64.135338, -21.895210),
('Cairo', 'Egypt', 'North Africa', 'Africa/Cairo', 'EGP', 50.00, 8, 'arid', 30.044420, 31.235712);

-- ACTIVITIES (5 per city = 100 activities)
INSERT INTO activities (city_id, name, category, avg_cost_usd, duration_hours, description, rating, group_suitable) VALUES
-- Mumbai (city_id = 1)
(1, 'Gateway of India Visit', 'sightseeing', 0.00, 2.0, 'Iconic colonial arch monument by the waterfront', 4.5, true),
(1, 'Dharavi Slum Tour', 'culture', 15.00, 3.0, 'Guided walk through one of Asia largest urban settlements', 4.3, true),
(1, 'Street Food Walk Colaba', 'food', 10.00, 2.5, 'Vada pav, pav bhaji and cutting chai trail', 4.7, true),
(1, 'Elephanta Caves Ferry', 'sightseeing', 12.00, 4.0, 'UNESCO rock-cut cave temples on Elephanta Island', 4.4, true),
(1, 'Bollywood Studio Tour', 'culture', 25.00, 3.0, 'Behind the scenes at Film City studios', 4.1, true),
-- Delhi (city_id = 2)
(2, 'Red Fort Exploration', 'sightseeing', 8.00, 3.0, 'Mughal-era fort and UNESCO World Heritage Site', 4.5, true),
(2, 'Chandni Chowk Food Trail', 'food', 12.00, 2.5, 'Parathas, jalebis and chaat in the oldest market', 4.8, true),
(2, 'Qutub Minar Complex', 'sightseeing', 6.00, 2.0, 'Tallest brick minaret in the world', 4.4, true),
(2, 'Humayuns Tomb Visit', 'culture', 8.00, 2.0, 'Persian-influenced Mughal architecture masterpiece', 4.3, false),
(2, 'Lodi Garden Evening Walk', 'nature', 0.00, 1.5, 'Peaceful gardens with medieval tombs', 4.2, true),
-- Goa (city_id = 3)
(3, 'Baga Beach Day', 'nature', 5.00, 5.0, 'Swimming, sunbathing and water sports', 4.6, true),
(3, 'Old Goa Churches Tour', 'culture', 0.00, 3.0, 'UNESCO World Heritage Portuguese cathedrals', 4.3, true),
(3, 'Sunset Cruise Mandovi River', 'nature', 18.00, 2.0, 'Boat cruise with live Goan music and dance', 4.5, true),
(3, 'Spice Plantation Tour', 'nature', 20.00, 3.0, 'Guided tour with traditional Goan lunch', 4.4, true),
(3, 'Anjuna Flea Market', 'shopping', 0.00, 2.5, 'Wednesday market with handicrafts and clothes', 4.1, true),
-- Jaipur (city_id = 4)
(4, 'Amber Fort Elephant Ride', 'sightseeing', 30.00, 4.0, 'Hilltop Rajput fort with elephant or jeep entry', 4.7, true),
(4, 'Hawa Mahal Photo Stop', 'sightseeing', 3.00, 1.0, 'Palace of Winds iconic pink facade', 4.4, true),
(4, 'City Palace Museum', 'culture', 10.00, 2.5, 'Royal residence turned museum with artefacts', 4.3, true),
(4, 'Bazaar Shopping Johari', 'shopping', 0.00, 2.0, 'Gems, jewellery and block-print textiles', 4.2, true),
(4, 'Jaipur Cooking Class', 'food', 25.00, 3.0, 'Learn dal baati churma and ghewar', 4.6, true),
-- Manali (city_id = 5)
(5, 'Rohtang Pass Snow Trip', 'adventure', 20.00, 8.0, 'High altitude pass with snow activities', 4.6, true),
(5, 'Solang Valley Skiing', 'adventure', 35.00, 4.0, 'Skiing and snowboarding slopes', 4.5, true),
(5, 'Hadimba Temple Visit', 'culture', 0.00, 1.5, 'Ancient wooden temple in cedar forest', 4.3, true),
(5, 'River Rafting Beas', 'adventure', 18.00, 2.0, 'Grade 2-3 white water rafting', 4.7, true),
(5, 'Old Manali Cafe Hop', 'food', 10.00, 2.0, 'Mountain cafes with maggi and apple juice', 4.4, true),
-- Paris (city_id = 6)
(6, 'Eiffel Tower Visit', 'sightseeing', 28.00, 3.0, 'Summit access with panoramic city views', 4.8, true),
(6, 'Louvre Museum', 'culture', 22.00, 4.0, 'Worlds largest art museum including Mona Lisa', 4.7, false),
(6, 'Seine River Cruise', 'sightseeing', 18.00, 1.5, 'Bateaux Mouches evening illumination cruise', 4.6, true),
(6, 'Montmartre Walking Tour', 'culture', 0.00, 2.5, 'Bohemian hilltop village with Sacre Coeur', 4.5, true),
(6, 'Paris Food Market Tour', 'food', 30.00, 3.0, 'Guided tasting at Marche d Aligre', 4.6, true),
-- Rome (city_id = 7)
(7, 'Colosseum Guided Tour', 'sightseeing', 35.00, 3.0, 'Ancient amphitheatre with arena floor access', 4.8, true),
(7, 'Vatican Museums Visit', 'culture', 30.00, 4.0, 'Sistine Chapel and St Peters Basilica', 4.7, true),
(7, 'Trastevere Food Walk', 'food', 25.00, 2.5, 'Pasta, supplì and gelato in old Rome', 4.7, true),
(7, 'Trevi Fountain Evening', 'sightseeing', 0.00, 1.0, 'Baroque fountain coin toss tradition', 4.5, true),
(7, 'Roman Cooking Class', 'food', 65.00, 3.5, 'Make cacio e pepe and tiramisu from scratch', 4.8, true),
-- Barcelona (city_id = 8)
(8, 'Sagrada Familia Tour', 'sightseeing', 32.00, 2.5, 'Gaudis unfinished masterpiece basilica', 4.9, true),
(8, 'Park Guell Visit', 'sightseeing', 12.00, 2.0, 'Mosaic terraces and city panorama', 4.6, true),
(8, 'La Boqueria Market', 'food', 15.00, 1.5, 'Famous covered market with fresh produce', 4.5, true),
(8, 'Gothic Quarter Walk', 'culture', 0.00, 2.0, 'Medieval lanes and hidden plazas', 4.4, true),
(8, 'Barcelona Tapas Tour', 'food', 40.00, 3.0, 'Evening pintxos and cava crawl', 4.7, true),
-- Amsterdam (city_id = 9)
(9, 'Anne Frank House', 'culture', 16.00, 2.0, 'Moving museum in the wartime hiding place', 4.7, false),
(9, 'Canal Boat Tour', 'sightseeing', 20.00, 1.5, 'Glass-roofed boat through historic canals', 4.6, true),
(9, 'Rijksmuseum Visit', 'culture', 22.00, 3.0, 'Rembrandt and Vermeer masterpieces', 4.7, false),
(9, 'Vondelpark Picnic', 'nature', 5.00, 2.0, 'Relax in Amsterdams favourite green space', 4.3, true),
(9, 'Dutch Cheese Tasting', 'food', 18.00, 1.5, 'Gouda and Edam tasting at a cheese shop', 4.4, true),
-- Prague (city_id = 10)
(10, 'Prague Castle Complex', 'sightseeing', 15.00, 3.5, 'Largest ancient castle in the world', 4.7, true),
(10, 'Charles Bridge Sunrise', 'sightseeing', 0.00, 1.0, 'Medieval bridge with baroque statues', 4.6, true),
(10, 'Old Town Square Tour', 'culture', 0.00, 2.0, 'Astronomical clock and Gothic church', 4.5, true),
(10, 'Czech Beer Tasting', 'food', 20.00, 2.0, 'Pilsner Urquell brewery pub experience', 4.6, true),
(10, 'Bohemian Cooking Class', 'food', 45.00, 3.0, 'Svickova and trdelnik hands-on class', 4.5, true),
-- Tokyo (city_id = 11)
(11, 'Senso-ji Temple Asakusa', 'culture', 0.00, 2.0, 'Tokyos oldest Buddhist temple with Nakamise market', 4.7, true),
(11, 'Shibuya Crossing Experience', 'sightseeing', 0.00, 1.0, 'Worlds busiest pedestrian scramble crossing', 4.5, true),
(11, 'Tsukiji Outer Market', 'food', 20.00, 2.0, 'Fresh sushi and street food at dawn', 4.7, true),
(11, 'teamLab Planets', 'sightseeing', 32.00, 2.0, 'Immersive digital art museum', 4.8, true),
(11, 'Tokyo Ramen Tour', 'food', 25.00, 2.5, 'Three iconic ramen shops in one evening', 4.8, true),
-- Bangkok (city_id = 12)
(12, 'Grand Palace Visit', 'sightseeing', 16.00, 3.0, 'Temple of the Emerald Buddha complex', 4.7, true),
(12, 'Floating Market Tour', 'culture', 25.00, 4.0, 'Damnoen Saduak canal market by longtail boat', 4.5, true),
(12, 'Street Food Night Tour', 'food', 20.00, 3.0, 'Pad thai, mango sticky rice and satay trail', 4.8, true),
(12, 'Muay Thai Evening Show', 'culture', 35.00, 2.5, 'Live Muay Thai boxing at Rajadamnern Stadium', 4.6, true),
(12, 'Thai Cooking Class', 'food', 30.00, 3.5, 'Tom yum and green curry from scratch', 4.7, true),
-- Bali (city_id = 13)
(13, 'Ubud Monkey Forest', 'nature', 5.00, 2.0, 'Sacred forest with long-tailed macaques', 4.4, true),
(13, 'Tegallalang Rice Terraces', 'nature', 3.00, 2.0, 'Iconic UNESCO-listed terraced rice fields', 4.6, true),
(13, 'Kecak Fire Dance Show', 'culture', 12.00, 1.5, 'Traditional Balinese sunset performance', 4.7, true),
(13, 'Mount Batur Sunrise Trek', 'adventure', 40.00, 6.0, 'Active volcano summit hike for sunrise', 4.8, true),
(13, 'Bali Cooking Class', 'food', 35.00, 4.0, 'Satay, lawar and black rice pudding', 4.7, true),
-- Singapore (city_id = 14)
(14, 'Gardens by the Bay', 'nature', 18.00, 3.0, 'Supertree Grove and Cloud Forest dome', 4.8, true),
(14, 'Marina Bay Sands Skypark', 'sightseeing', 26.00, 1.5, '57th floor infinity pool and observation deck', 4.7, false),
(14, 'Hawker Centre Food Tour', 'food', 15.00, 2.0, 'Chicken rice, laksa and chilli crab at Maxwell', 4.8, true),
(14, 'Sentosa Island Day', 'adventure', 30.00, 5.0, 'Universal Studios and beach in one day', 4.6, true),
(14, 'Chinatown Heritage Walk', 'culture', 0.00, 2.0, 'Temples, shophouses and street art', 4.4, true),
-- Dubai (city_id = 15)
(15, 'Burj Khalifa At The Top', 'sightseeing', 40.00, 2.0, '124th floor observation deck views', 4.7, true),
(15, 'Desert Safari Dune Bashing', 'adventure', 55.00, 6.0, '4x4 dunes, camel ride and BBQ dinner', 4.8, true),
(15, 'Dubai Creek Abra Ride', 'culture', 1.00, 0.5, 'Traditional wooden boat across the old creek', 4.3, true),
(15, 'Dubai Food Tour Deira', 'food', 30.00, 3.0, 'Shawarma, luqaimat and karak chai trail', 4.6, true),
(15, 'Dubai Mall Ice Rink', 'adventure', 25.00, 2.0, 'Olympic-size rink inside the worlds largest mall', 4.4, true),
-- New York (city_id = 16)
(16, 'Central Park Walking Tour', 'nature', 0.00, 3.0, 'Bethesda Fountain, Bow Bridge and The Ramble', 4.6, true),
(16, 'Manhattan Food Tour', 'food', 45.00, 3.0, 'Pizza, bagels and cheesecake across three boroughs', 4.7, true),
(16, 'High Line Walk', 'sightseeing', 0.00, 2.0, 'Elevated park on former rail line with art', 4.6, true),
(16, 'MoMA Visit', 'culture', 30.00, 3.0, 'Van Gogh, Picasso and Warhol in one building', 4.7, false),
(16, 'Brooklyn Bridge Walk', 'sightseeing', 0.00, 1.5, 'Walk across with Manhattan skyline views', 4.7, true),
-- London (city_id = 17)
(17, 'Tower of London Tour', 'culture', 35.00, 3.0, 'Crown Jewels and Beefeater guided walk', 4.7, true),
(17, 'Borough Market Food Tour', 'food', 25.00, 2.0, 'Artisan cheeses, pies and international street food', 4.7, true),
(17, 'Thames Riverboat Cruise', 'sightseeing', 20.00, 1.5, 'Westminster to Greenwich with commentary', 4.5, true),
(17, 'British Museum Visit', 'culture', 0.00, 3.5, 'Rosetta Stone and Elgin Marbles free admission', 4.7, true),
(17, 'Notting Hill Walk', 'sightseeing', 0.00, 2.0, 'Colourful houses and Portobello Road market', 4.4, true),
-- Sydney (city_id = 18)
(18, 'Sydney Opera House Tour', 'culture', 42.00, 1.5, 'Backstage guided tour of the iconic sails', 4.7, true),
(18, 'Bondi to Coogee Coastal Walk', 'nature', 0.00, 3.0, 'Clifftop ocean trail past six beaches', 4.8, true),
(18, 'Sydney Harbour Bridge Climb', 'adventure', 180.00, 3.5, 'Summit climb of the harbour bridge pylons', 4.9, true),
(18, 'Taronga Zoo Visit', 'nature', 45.00, 4.0, 'Native Australian wildlife with harbour views', 4.6, true),
(18, 'Rocks Historical Walk', 'culture', 0.00, 2.0, 'Convict-era sandstone laneways and pubs', 4.3, true),
-- Reykjavik (city_id = 19)
(19, 'Northern Lights Tour', 'nature', 80.00, 4.0, 'Aurora hunting by minibus outside the city', 4.8, true),
(19, 'Golden Circle Day Trip', 'nature', 90.00, 8.0, 'Geysir, Gullfoss waterfall and Thingvellir', 4.9, true),
(19, 'Blue Lagoon Geothermal Spa', 'wellness', 70.00, 3.0, 'Famous milky-blue geothermal pool', 4.7, true),
(19, 'Reykjavik Food Walk', 'food', 55.00, 2.5, 'Skyr, lamb soup and fermented shark tasting', 4.5, true),
(19, 'Whale Watching Cruise', 'nature', 85.00, 3.0, 'Humpback and minke whale sightings from Faxafloi', 4.7, true),
-- Cairo (city_id = 20)
(20, 'Giza Pyramids and Sphinx', 'sightseeing', 20.00, 4.0, 'The last surviving ancient wonder of the world', 4.9, true),
(20, 'Egyptian Museum Visit', 'culture', 15.00, 3.0, 'Tutankhamun treasures and royal mummies', 4.7, true),
(20, 'Khan el-Khalili Bazaar', 'shopping', 0.00, 2.5, 'Medieval Islamic market for spices and souvenirs', 4.5, true),
(20, 'Nile Dinner Cruise', 'food', 35.00, 3.0, 'Egyptian buffet with belly dancing on the Nile', 4.5, true),
(20, 'Saqqara Step Pyramid Trip', 'sightseeing', 18.00, 4.0, 'Oldest standing pyramid complex outside Giza', 4.6, true);

-- PACKING TEMPLATES (covers all 5 climate zones)
INSERT INTO packing_templates (climate_zone, category, item_label, priority) VALUES
-- Tropical
('tropical', 'clothing', 'Lightweight breathable t-shirts', 'must'),
('tropical', 'clothing', 'Shorts and linen trousers', 'must'),
('tropical', 'clothing', 'Flip flops and sandals', 'must'),
('tropical', 'clothing', 'Light rain jacket', 'recommended'),
('tropical', 'clothing', 'Swimwear', 'must'),
('tropical', 'toiletries', 'High SPF sunscreen (SPF 50+)', 'must'),
('tropical', 'toiletries', 'Insect repellent (DEET-based)', 'must'),
('tropical', 'toiletries', 'After-sun lotion', 'recommended'),
('tropical', 'toiletries', 'Rehydration sachets', 'recommended'),
('tropical', 'documents', 'Travel insurance with medical cover', 'must'),
('tropical', 'other', 'Reusable water bottle', 'must'),
('tropical', 'other', 'Portable fan', 'optional'),
-- Temperate
('temperate', 'clothing', 'Layering base shirts', 'must'),
('temperate', 'clothing', 'Mid-layer fleece or jumper', 'must'),
('temperate', 'clothing', 'Waterproof jacket', 'must'),
('temperate', 'clothing', 'Comfortable walking shoes', 'must'),
('temperate', 'clothing', 'Smart casual outfit for dinners', 'recommended'),
('temperate', 'toiletries', 'Moisturiser for dry air', 'recommended'),
('temperate', 'toiletries', 'Lip balm', 'recommended'),
('temperate', 'documents', 'Travel insurance', 'must'),
('temperate', 'other', 'Compact umbrella', 'must'),
('temperate', 'other', 'Day backpack', 'must'),
-- Cold
('cold', 'clothing', 'Thermal base layer top and bottom', 'must'),
('cold', 'clothing', 'Heavy down jacket', 'must'),
('cold', 'clothing', 'Wool socks (3+ pairs)', 'must'),
('cold', 'clothing', 'Waterproof insulated boots', 'must'),
('cold', 'clothing', 'Gloves and thermal beanie', 'must'),
('cold', 'clothing', 'Fleece mid-layer', 'must'),
('cold', 'clothing', 'Neck gaiter or scarf', 'recommended'),
('cold', 'toiletries', 'Heavy duty moisturiser', 'must'),
('cold', 'toiletries', 'Lip balm SPF', 'must'),
('cold', 'toiletries', 'Hand cream', 'recommended'),
('cold', 'other', 'Hand warmers', 'recommended'),
('cold', 'other', 'Thermos flask', 'recommended'),
-- Arid
('arid', 'clothing', 'Loose long-sleeve shirts for sun cover', 'must'),
('arid', 'clothing', 'Wide brim hat', 'must'),
('arid', 'clothing', 'Lightweight long trousers', 'must'),
('arid', 'clothing', 'Closed-toe sandals', 'recommended'),
('arid', 'toiletries', 'SPF 50+ sunscreen', 'must'),
('arid', 'toiletries', 'Lip balm with SPF', 'must'),
('arid', 'toiletries', 'Eye drops for dry air', 'recommended'),
('arid', 'other', 'Large reusable water bottle (2L)', 'must'),
('arid', 'other', 'Electrolyte tablets', 'must'),
('arid', 'other', 'Sunglasses UV400', 'must'),
-- Variable
('variable', 'clothing', 'Mix of light and warm layers', 'must'),
('variable', 'clothing', 'Waterproof jacket', 'must'),
('variable', 'clothing', 'Versatile walking shoes', 'must'),
('variable', 'clothing', 'Light scarf (doubles as blanket)', 'recommended'),
('variable', 'toiletries', 'All-weather moisturiser', 'recommended'),
('variable', 'documents', 'Printed hotel and flight confirmations', 'recommended'),
('variable', 'other', 'Compact umbrella', 'must'),
('variable', 'other', 'Portable power bank', 'must'),
-- Universal documents (add to all trips regardless of climate)
('tropical', 'documents', 'Passport with 6 months validity', 'must'),
('temperate', 'documents', 'Passport with 6 months validity', 'must'),
('cold', 'documents', 'Passport with 6 months validity', 'must'),
('arid', 'documents', 'Passport with 6 months validity', 'must'),
('variable', 'documents', 'Passport with 6 months validity', 'must'),
('tropical', 'electronics', 'Universal travel adapter', 'must'),
('temperate', 'electronics', 'Universal travel adapter', 'must'),
('cold', 'electronics', 'Universal travel adapter', 'must'),
('arid', 'electronics', 'Universal travel adapter', 'must'),
('variable', 'electronics', 'Universal travel adapter', 'must'),
('tropical', 'electronics', 'Portable power bank', 'must'),
('temperate', 'electronics', 'Portable power bank', 'must'),
('cold', 'electronics', 'Portable power bank 20000mAh for cold battery drain', 'must'),
('arid', 'electronics', 'Portable power bank', 'must'),
('variable', 'electronics', 'Portable power bank', 'must');
